config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :trabalhos
  resources :provas
  resources :nota_alunos
  resources :disciplinas
  resources :professores
  resources :atividades_extras
  resources :nota_prova_livros
  resources :notas_trabalhos
  resources :presenca_aulas
  resources :matriculas
  resources :aulas
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    belongs_to :disciplina, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :prova, optional: true
    belongs_to :curso, optional: true
    belongs_to :professor, optional: true
    belongs_to :matricula, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :documento, :telefone, :email, :pai, :mae, :endereco, presence: true
    validates :email, uniqueness: true 

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atividades_extra.rb
class AtividadesExtra < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :data_entrega, :curso, :disciplina, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/aula.rb
class Aula < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :presenca_aula, class_name: "Presenca aula" 

    validates :disciplina, :data, :objetivo, :realizado, presence:true

    scope :por_disciplina, lambda { |disciplina = nil|
        where(disciplina: disciplina) if disciplina
    }
end
 

app/models/curso.rb
class Curso < ApplicationRecord
    belongs_to :disciplina, optional: true

    validates :nome, presence:true
    validates :nome, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :curso, optional: true

    has_many :aluno, class_name: "Aluno"

    validates :nome, :curso, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/matricula.rb
class Matricula < ApplicationRecord
    belongs_to :aluno, optional: true

    validates :ra, :nome, :curso, :disciplina, :endereco, :cpf, :data, :semestre, presence:true

    scope :por_ra, lambda { |ra = nil|
    where(ra: ra) if ra
}
end
 

app/models/nota_aluno.rb
class NotaAluno < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :nota_prova_livro, optional;true
 


    has_many :aluno, class_name: "Aluno"

    validates :nome_do_aluno, :nota_g1, :nota_g2, :sub_g1, :sub_g2, :data_prova, presence:true

    scope :por_nome_do_aluno, lambda { |nome_do_aluno = nil|
    where(nome_do_aluno: nome_do_aluno) if nome_do_aluno
}
end
 

app/models/nota_prova_livro.rb
class NotaProvaLivro < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :curso, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/notas_trabalho.rb
class NotasTrabalho < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :trabalho, optional: true
    
    has_many :aluno, class_name: "Aluno"

    validates :nome, :data, :curso, :disciplina, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/presenca_aula.rb
class PresencaAula < ApplicationRecord
    belongs_to :professor, optional: true

    has_many :aluno, class_name: "Aluno"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :data, :numero_faltas, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/professor.rb
class Professor < ApplicationRecord
    belongs_to :prova, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :aluno, optional: true
    belongs_to :presenca_aula, optional: true
    belongs_to :atividades_extra, optional: true
    
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :presencas_aula, class_name: "Presenca aula"

    validates :nome, :documento, :email, :telefone, :endereco, presence:true
    validates :email, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/prova.rb
class Prova < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true
    belongs_to :disciplina, optional: true
    belongs_to :curso, optional: true

    has_many :prova, class_name: "Prova"
    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :disciplina, :nota_aluno, :curso, :data, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :notas_trabalho, class_name:"Nota trabalho"

    validates :nome, :disciplina, :curso, :data_de_entrega, :descricao, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/controllers/provas_controller.rb
class ProvasController < ApplicationController
  before_action :set_prova, only: [:show, :edit, :update, :destroy]

  # GET /provas
  # GET /provas.json
  def index
    @provas = Prova.all
  end

  # GET /provas/1
  # GET /provas/1.json
  def show
  end

  # GET /provas/new
  def new
    @prova = Prova.new
  end

  # GET /provas/1/edit
  def edit
  end

  # POST /provas
  # POST /provas.json
  def create
    @prova = Prova.new(prova_params)

    respond_to do |format|
      if @prova.save
        format.html { redirect_to @prova, notice: 'Prova was successfully created.' }
        format.json { render :show, status: :created, location: @prova }
      else
        format.html { render :new }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provas/1
  # PATCH/PUT /provas/1.json
  def update
    respond_to do |format|
      if @prova.update(prova_params)
        format.html { redirect_to @prova, notice: 'Prova was successfully updated.' }
        format.json { render :show, status: :ok, location: @prova }
      else
        format.html { render :edit }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provas/1
  # DELETE /provas/1.json
  def destroy
    @prova.destroy
    respond_to do |format|
      format.html { redirect_to provas_url, notice: 'Prova was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prova
      @prova = Prova.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prova_params
      params.require(:prova).permit(:nome, :disciplina, :nota_aluno, :curso, :data)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/provas/_form.html.erb
<%= form_with(model: prova, local: true) do |form| %>
  <% if prova.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prova.errors.count, "error") %> prohibited this prova from being saved:</h2>

      <ul>
      <% prova.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :disciplina %>
    <%= form.text_field :disciplina %>
  </div>

  <div class="field">
    <%= form.label :nota_aluno %>
    <%= form.number_field :nota_aluno %>
  </div>

  <div class="field">
    <%= form.label :curso %>
    <%= form.text_field :curso %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :professores_id %>
    <%= form.select(:professores_id, 
                    Professor.all.collect {|p| [p.nome, p.id]}) %>
</div>

<div class="field">
<%= form.label :alunos_id %>
<%= form.select(:alunos_id, 
                Aluno.all.collect {|a| [a.nome, a.id]}) %>
</div>

<div class="field">
    <%= form.label :disciplinas_id %>
    <%= form.select(:disciplinas_id, 
                    Disciplina.all.collect {|d| [d.nome, d.id]}) %>
</div>

<div class="field">
<%= form.label :cursos_id %>
<%= form.select(:cursos_id, 
                Curso.all.collect {|c| [c.nome, c.id]}) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provas/edit.html.erb
<h1>Editing Prova</h1>

<%= render 'form', prova: @prova %>

<%= link_to 'Show', @prova %> |
<%= link_to 'Back', provas_path %>

app/views/provas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Disciplina</th>
      <th>Nota aluno</th>
      <th>Curso</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provas.each do |prova| %>
      <tr>
        <td><%= prova.nome %></td>
        <td><%= prova.disciplina %></td>
        <td><%= prova.nota_aluno %></td>
        <td><%= prova.curso %></td>
        <td><%= prova.data %></td>
        <td><%= link_to 'Show', prova %></td>
        <td><%= link_to 'Edit', edit_prova_path(prova) %></td>
        <td><%= link_to 'Destroy', prova, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prova', new_prova_path %>

app/views/provas/new.html.erb
<h1>New Prova</h1>

<%= render 'form', prova: @prova %>

<%= link_to 'Back', provas_path %>

app/views/provas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @prova.nome %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @prova.disciplina %>
</p>

<p>
  <strong>Nota aluno:</strong>
  <%= @prova.nota_aluno %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @prova.curso %>
</p>

<p>
  <strong>Data:</strong>
  <%= @prova.data %>
</p>

<%= link_to 'Edit', edit_prova_path(@prova) %> |
<%= link_to 'Back', provas_path %>