config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :trabalhos
  resources :provas
  resources :nota_alunos
  resources :disciplinas
  resources :professores
  resources :atividades_extras
  resources :nota_prova_livros
  resources :notas_trabalhos
  resources :presenca_aulas
  resources :matriculas
  resources :aulas
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    belongs_to :disciplina, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :prova, optional: true
    belongs_to :curso, optional: true
    belongs_to :professor, optional: true
    belongs_to :matricula, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :documento, :telefone, :email, :pai, :mae, :endereco, presence: true
    validates :email, uniqueness: true 

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atividades_extra.rb
class AtividadesExtra < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :data_entrega, :curso, :disciplina, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/aula.rb
class Aula < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :presenca_aula, class_name: "Presenca aula" 

    validates :disciplina, :data, :objetivo, :realizado, presence:true

    scope :por_disciplina, lambda { |disciplina = nil|
        where(disciplina: disciplina) if disciplina
    }
end
 

app/models/curso.rb
class Curso < ApplicationRecord
    belongs_to :disciplina, optional: true

    validates :nome, presence:true
    validates :nome, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :curso, optional: true

    has_many :aluno, class_name: "Aluno"

    validates :nome, :curso, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/matricula.rb
class Matricula < ApplicationRecord
    belongs_to :aluno, optional: true

    validates :ra, :nome, :curso, :disciplina, :endereco, :cpf, :data, :semestre, presence:true

    scope :por_ra, lambda { |ra = nil|
    where(ra: ra) if ra
}
end
 

app/models/nota_aluno.rb
class NotaAluno < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :nota_prova_livro, optional;true
 


    has_many :aluno, class_name: "Aluno"

    validates :nome_do_aluno, :nota_g1, :nota_g2, :sub_g1, :sub_g2, :data_prova, presence:true

    scope :por_nome_do_aluno, lambda { |nome_do_aluno = nil|
    where(nome_do_aluno: nome_do_aluno) if nome_do_aluno
}
end
 

app/models/nota_prova_livro.rb
class NotaProvaLivro < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :curso, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/notas_trabalho.rb
class NotasTrabalho < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :trabalho, optional: true
    
    has_many :aluno, class_name: "Aluno"

    validates :nome, :data, :curso, :disciplina, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/presenca_aula.rb
class PresencaAula < ApplicationRecord
    belongs_to :professor, optional: true

    has_many :aluno, class_name: "Aluno"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :data, :numero_faltas, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/professor.rb
class Professor < ApplicationRecord
    belongs_to :prova, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :aluno, optional: true
    belongs_to :presenca_aula, optional: true
    belongs_to :atividades_extra, optional: true
    
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :presencas_aula, class_name: "Presenca aula"

    validates :nome, :documento, :email, :telefone, :endereco, presence:true
    validates :email, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/prova.rb
class Prova < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true
    belongs_to :disciplina, optional: true
    belongs_to :curso, optional: true

    has_many :prova, class_name: "Prova"
    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :disciplina, :nota_aluno, :curso, :data, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :notas_trabalho, class_name:"Nota trabalho"

    validates :nome, :disciplina, :curso, :data_de_entrega, :descricao, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :email, :endereco, :pai, :mae, :documento, :telefone)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_area :endereco %>
  </div>

  <div class="field">
    <%= form.label :pai %>
    <%= form.text_field :pai %>
  </div>

  <div class="field">
    <%= form.label :mae %>
    <%= form.text_field :mae %>
  </div>

  <div class="field">
    <%= form.label :documento %>
    <%= form.text_field :documento %>
  </div>
  
  <div class="field">
    <%= form.label :telefone %>
    <%= form.number_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :disciplinas_id %>
    <%= form.select(:disciplinas_id, 
                    Disciplina.all.collect {|d| [d.nome, d.id]}) %>
</div>

<div class="field">
<%= form.label :trabalhos_id %>
<%= form.select(:trabalhos_id, 
                Trabalho.all.collect {|t| [t.nome, t.id]}) %>
</div>

<div class="field">
<%= form.label :provas_id %>
<%= form.select(:provas_id, 
                Prova.all.collect {|p| [p.nome, p.id]}) %>
</div>

<div class="field">
<%= form.label :cursos_id %>
<%= form.select(:cursos_id, 
                Curso.all.collect {|c| [c.nome, c.id]}) %>
</div>

<div class="field">
<%= form.label :professores_id %>
<%= form.select(:professores_id, 
                Professor.all.collect {|pr| [pr.nome, pr.id]}) %>
</div>

<div class="field">
<%= form.label :matriculas_id %>
<%= form.select(:matriculas_id, 
                Matricula.all.collect {|m| [m.ra, m.id]}) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Endereco</th>
      <th>Pai</th>
      <th>Mae</th>
      <th>Documento</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.email %></td>
        <td><%= aluno.endereco %></td>
        <td><%= aluno.pai %></td>
        <td><%= aluno.mae %></td>
        <td><%= aluno.documento %></td>
        <td><%= aluno.telefone %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @aluno.endereco %>
</p>

<p>
  <strong>Pai:</strong>
  <%= @aluno.pai %>
</p>

<p>
  <strong>Mae:</strong>
  <%= @aluno.mae %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @aluno.documento %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @aluno.telefone %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>