config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :trabalhos
  resources :provas
  resources :nota_alunos
  resources :disciplinas
  resources :professores
  resources :atividades_extras
  resources :nota_prova_livros
  resources :notas_trabalhos
  resources :presenca_aulas
  resources :matriculas
  resources :aulas
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    belongs_to :disciplina, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :prova, optional: true
    belongs_to :curso, optional: true
    belongs_to :professor, optional: true
    belongs_to :matricula, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :documento, :telefone, :email, :pai, :mae, :endereco, presence: true
    validates :email, uniqueness: true 

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/atividades_extra.rb
class AtividadesExtra < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :data_entrega, :curso, :disciplina, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/aula.rb
class Aula < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :presenca_aula, class_name: "Presenca aula" 

    validates :disciplina, :data, :objetivo, :realizado, presence:true

    scope :por_disciplina, lambda { |disciplina = nil|
        where(disciplina: disciplina) if disciplina
    }
end
 

app/models/curso.rb
class Curso < ApplicationRecord
    belongs_to :disciplina, optional: true

    validates :nome, presence:true
    validates :nome, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :curso, optional: true

    has_many :aluno, class_name: "Aluno"

    validates :nome, :curso, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/matricula.rb
class Matricula < ApplicationRecord
    belongs_to :aluno, optional: true

    validates :ra, :nome, :curso, :disciplina, :endereco, :cpf, :data, :semestre, presence:true

    scope :por_ra, lambda { |ra = nil|
    where(ra: ra) if ra
}
end
 

app/models/nota_aluno.rb
class NotaAluno < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :nota_prova_livro, optional;true
 


    has_many :aluno, class_name: "Aluno"

    validates :nome_do_aluno, :nota_g1, :nota_g2, :sub_g1, :sub_g2, :data_prova, presence:true

    scope :por_nome_do_aluno, lambda { |nome_do_aluno = nil|
    where(nome_do_aluno: nome_do_aluno) if nome_do_aluno
}
end
 

app/models/nota_prova_livro.rb
class NotaProvaLivro < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :curso, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/notas_trabalho.rb
class NotasTrabalho < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :trabalho, optional: true
    
    has_many :aluno, class_name: "Aluno"

    validates :nome, :data, :curso, :disciplina, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/presenca_aula.rb
class PresencaAula < ApplicationRecord
    belongs_to :professor, optional: true

    has_many :aluno, class_name: "Aluno"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :data, :numero_faltas, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/professor.rb
class Professor < ApplicationRecord
    belongs_to :prova, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :aluno, optional: true
    belongs_to :presenca_aula, optional: true
    belongs_to :atividades_extra, optional: true
    
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :presencas_aula, class_name: "Presenca aula"

    validates :nome, :documento, :email, :telefone, :endereco, presence:true
    validates :email, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/prova.rb
class Prova < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true
    belongs_to :disciplina, optional: true
    belongs_to :curso, optional: true

    has_many :prova, class_name: "Prova"
    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :disciplina, :nota_aluno, :curso, :data, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :notas_trabalho, class_name:"Nota trabalho"

    validates :nome, :disciplina, :curso, :data_de_entrega, :descricao, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/controllers/nota_prova_livros_controller.rb
class NotaProvaLivrosController < ApplicationController
  before_action :set_nota_prova_livro, only: [:show, :edit, :update, :destroy]

  # GET /nota_prova_livros
  # GET /nota_prova_livros.json
  def index
    @nota_prova_livros = NotaProvaLivro.all
  end

  # GET /nota_prova_livros/1
  # GET /nota_prova_livros/1.json
  def show
  end

  # GET /nota_prova_livros/new
  def new
    @nota_prova_livro = NotaProvaLivro.new
  end

  # GET /nota_prova_livros/1/edit
  def edit
  end

  # POST /nota_prova_livros
  # POST /nota_prova_livros.json
  def create
    @nota_prova_livro = NotaProvaLivro.new(nota_prova_livro_params)

    respond_to do |format|
      if @nota_prova_livro.save
        format.html { redirect_to @nota_prova_livro, notice: 'Nota prova livro was successfully created.' }
        format.json { render :show, status: :created, location: @nota_prova_livro }
      else
        format.html { render :new }
        format.json { render json: @nota_prova_livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota_prova_livros/1
  # PATCH/PUT /nota_prova_livros/1.json
  def update
    respond_to do |format|
      if @nota_prova_livro.update(nota_prova_livro_params)
        format.html { redirect_to @nota_prova_livro, notice: 'Nota prova livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @nota_prova_livro }
      else
        format.html { render :edit }
        format.json { render json: @nota_prova_livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota_prova_livros/1
  # DELETE /nota_prova_livros/1.json
  def destroy
    @nota_prova_livro.destroy
    respond_to do |format|
      format.html { redirect_to nota_prova_livros_url, notice: 'Nota prova livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota_prova_livro
      @nota_prova_livro = NotaProvaLivro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nota_prova_livro_params
      params.require(:nota_prova_livro).permit(:nome, :data, :curso, :nota_aluno)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/nota_prova_livros_helper.rb
module NotaProvaLivrosHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/nota_prova_livros/_form.html.erb
<%= form_with(model: nota_prova_livro, local: true) do |form| %>
  <% if nota_prova_livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nota_prova_livro.errors.count, "error") %> prohibited this nota_prova_livro from being saved:</h2>

      <ul>
      <% nota_prova_livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data %>
  </div>

  <div class="field">
    <%= form.label :curso %>
    <%= form.text_field :curso %>
  </div>

  <div class="field">
    <%= form.label :nota_aluno %>
    <%= form.number_field :nota_aluno %>
  </div>

  <div class="field">
    <%= form.label :professores_id %>
    <%= form.select(:professores_id, 
                    Professor.all.collect {|p| [p.nome, p.id]}) %>
</div>

<div class="field">
<%= form.label :alunos_id %>
<%= form.select(:alunos_id, 
                Aluno.all.collect {|a| [a.nome, a.id]}) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nota_prova_livros/edit.html.erb
<h1>Editing Nota Prova Livro</h1>

<%= render 'form', nota_prova_livro: @nota_prova_livro %>

<%= link_to 'Show', @nota_prova_livro %> |
<%= link_to 'Back', nota_prova_livros_path %>

app/views/nota_prova_livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nota Prova Livros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data</th>
      <th>Curso</th>
      <th>Nota aluno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nota_prova_livros.each do |nota_prova_livro| %>
      <tr>
        <td><%= nota_prova_livro.nome %></td>
        <td><%= nota_prova_livro.data %></td>
        <td><%= nota_prova_livro.curso %></td>
        <td><%= nota_prova_livro.nota_aluno %></td>
        <td><%= link_to 'Show', nota_prova_livro %></td>
        <td><%= link_to 'Edit', edit_nota_prova_livro_path(nota_prova_livro) %></td>
        <td><%= link_to 'Destroy', nota_prova_livro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nota Prova Livro', new_nota_prova_livro_path %>

app/views/nota_prova_livros/new.html.erb
<h1>New Nota Prova Livro</h1>

<%= render 'form', nota_prova_livro: @nota_prova_livro %>

<%= link_to 'Back', nota_prova_livros_path %>

app/views/nota_prova_livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @nota_prova_livro.nome %>
</p>

<p>
  <strong>Data:</strong>
  <%= @nota_prova_livro.data %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @nota_prova_livro.curso %>
</p>

<p>
  <strong>Nota aluno:</strong>
  <%= @nota_prova_livro.nota_aluno %>
</p>

<%= link_to 'Edit', edit_nota_prova_livro_path(@nota_prova_livro) %> |
<%= link_to 'Back', nota_prova_livros_path %>