config/routes.rb
Rails.application.routes.draw do
  resources :cursos
  resources :trabalhos
  resources :provas
  resources :nota_alunos
  resources :disciplinas
  resources :professores
  resources :atividades_extras
  resources :nota_prova_livros
  resources :notas_trabalhos
  resources :presenca_aulas
  resources :matriculas
  resources :aulas
  resources :alunos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    belongs_to :disciplina, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :prova, optional: true
    belongs_to :curso, optional: true
    belongs_to :professor, optional: true
    belongs_to :matricula, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :documento, :telefone, :email, :pai, :mae, :endereco, presence: true
    validates :email, uniqueness: true 

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atividades_extra.rb
class AtividadesExtra < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :data_entrega, :curso, :disciplina, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/aula.rb
class Aula < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :presenca_aula, class_name: "Presenca aula" 

    validates :disciplina, :data, :objetivo, :realizado, presence:true

    scope :por_disciplina, lambda { |disciplina = nil|
        where(disciplina: disciplina) if disciplina
    }
end
 

app/models/curso.rb
class Curso < ApplicationRecord
    belongs_to :disciplina, optional: true

    validates :nome, presence:true
    validates :nome, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :curso, optional: true

    has_many :aluno, class_name: "Aluno"

    validates :nome, :curso, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/matricula.rb
class Matricula < ApplicationRecord
    belongs_to :aluno, optional: true

    validates :ra, :nome, :curso, :disciplina, :endereco, :cpf, :data, :semestre, presence:true

    scope :por_ra, lambda { |ra = nil|
    where(ra: ra) if ra
}
end
 

app/models/nota_aluno.rb
class NotaAluno < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :nota_prova_livro, optional;true
 


    has_many :aluno, class_name: "Aluno"

    validates :nome_do_aluno, :nota_g1, :nota_g2, :sub_g1, :sub_g2, :data_prova, presence:true

    scope :por_nome_do_aluno, lambda { |nome_do_aluno = nil|
    where(nome_do_aluno: nome_do_aluno) if nome_do_aluno
}
end
 

app/models/nota_prova_livro.rb
class NotaProvaLivro < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true

    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :data, :curso, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/notas_trabalho.rb
class NotasTrabalho < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :trabalho, optional: true
    
    has_many :aluno, class_name: "Aluno"

    validates :nome, :data, :curso, :disciplina, :nota_aluno, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/presenca_aula.rb
class PresencaAula < ApplicationRecord
    belongs_to :professor, optional: true

    has_many :aluno, class_name: "Aluno"
    has_many :presenca_aula, class_name: "Presenca aula"

    validates :nome, :data, :numero_faltas, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/professor.rb
class Professor < ApplicationRecord
    belongs_to :prova, optional: true
    belongs_to :trabalho, optional: true
    belongs_to :aluno, optional: true
    belongs_to :presenca_aula, optional: true
    belongs_to :atividades_extra, optional: true
    
    has_many :notas_trabalho, class_name: "Nota trabalho"
    has_many :nota_alunos, class_name: "Nota aluno"
    has_many :presencas_aula, class_name: "Presenca aula"

    validates :nome, :documento, :email, :telefone, :endereco, presence:true
    validates :email, uniqueness: true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/models/prova.rb
class Prova < ApplicationRecord
    belongs_to :professor, optional: true
    belongs_to :aluno, optional: true
    belongs_to :disciplina, optional: true
    belongs_to :curso, optional: true

    has_many :prova, class_name: "Prova"
    has_many :nota_alunos, class_name: "Nota aluno"

    validates :nome, :disciplina, :nota_aluno, :curso, :data, presence:true

    scope :por_nome, lambda { |nome = nil|
    where(nome: nome) if nome
}
end

app/models/trabalho.rb
class Trabalho < ApplicationRecord
    belongs_to :aluno, optional: true
    belongs_to :professor, optional: true

    has_many :notas_trabalho, class_name:"Nota trabalho"

    validates :nome, :disciplina, :curso, :data_de_entrega, :descricao, presence:true

    scope :por_nome, lambda { |nome = nil|
        where(nome: nome) if nome
    }
end

app/controllers/trabalhos_controller.rb
class TrabalhosController < ApplicationController
  before_action :set_trabalho, only: [:show, :edit, :update, :destroy]

  # GET /trabalhos
  # GET /trabalhos.json
  def index
    @trabalhos = Trabalho.all
  end

  # GET /trabalhos/1
  # GET /trabalhos/1.json
  def show
  end

  # GET /trabalhos/new
  def new
    @trabalho = Trabalho.new
  end

  # GET /trabalhos/1/edit
  def edit
  end

  # POST /trabalhos
  # POST /trabalhos.json
  def create
    @trabalho = Trabalho.new(trabalho_params)

    respond_to do |format|
      if @trabalho.save
        format.html { redirect_to @trabalho, notice: 'Trabalho was successfully created.' }
        format.json { render :show, status: :created, location: @trabalho }
      else
        format.html { render :new }
        format.json { render json: @trabalho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabalhos/1
  # PATCH/PUT /trabalhos/1.json
  def update
    respond_to do |format|
      if @trabalho.update(trabalho_params)
        format.html { redirect_to @trabalho, notice: 'Trabalho was successfully updated.' }
        format.json { render :show, status: :ok, location: @trabalho }
      else
        format.html { render :edit }
        format.json { render json: @trabalho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabalhos/1
  # DELETE /trabalhos/1.json
  def destroy
    @trabalho.destroy
    respond_to do |format|
      format.html { redirect_to trabalhos_url, notice: 'Trabalho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabalho
      @trabalho = Trabalho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trabalho_params
      params.require(:trabalho).permit(:nome, :disciplina, :curso, :data_de_entrega, :descricao)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/trabalhos_helper.rb
module TrabalhosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/trabalhos/_form.html.erb
<%= form_with(model: trabalho, local: true) do |form| %>
  <% if trabalho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trabalho.errors.count, "error") %> prohibited this trabalho from being saved:</h2>

      <ul>
      <% trabalho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :disciplina %>
    <%= form.text_field :disciplina %>
  </div>

  <div class="field">
    <%= form.label :curso %>
    <%= form.text_field :curso %>
  </div>

  <div class="field">
    <%= form.label :data_de_entrega %>
    <%= form.date_select :data_de_entrega %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao %>
  </div>

<div class="field">
<%= form.label :alunos_id %>
<%= form.select(:alunos_id, 
                Aluno.all.collect {|a| [a.nome, a.id]}) %>
</div>

<div class="field">
    <%= form.label :professores_id %>
    <%= form.select(:professores_id, 
                    Professor.all.collect {|p| [p.nome, p.id]}) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trabalhos/edit.html.erb
<h1>Editing Trabalho</h1>

<%= render 'form', trabalho: @trabalho %>

<%= link_to 'Show', @trabalho %> |
<%= link_to 'Back', trabalhos_path %>

app/views/trabalhos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trabalhos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Disciplina</th>
      <th>Curso</th>
      <th>Data de entrega</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trabalhos.each do |trabalho| %>
      <tr>
        <td><%= trabalho.nome %></td>
        <td><%= trabalho.disciplina %></td>
        <td><%= trabalho.curso %></td>
        <td><%= trabalho.data_de_entrega %></td>
        <td><%= trabalho.descricao %></td>
        <td><%= link_to 'Show', trabalho %></td>
        <td><%= link_to 'Edit', edit_trabalho_path(trabalho) %></td>
        <td><%= link_to 'Destroy', trabalho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trabalho', new_trabalho_path %>

app/views/trabalhos/new.html.erb
<h1>New Trabalho</h1>

<%= render 'form', trabalho: @trabalho %>

<%= link_to 'Back', trabalhos_path %>

app/views/trabalhos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @trabalho.nome %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @trabalho.disciplina %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @trabalho.curso %>
</p>

<p>
  <strong>Data de entrega:</strong>
  <%= @trabalho.data_de_entrega %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @trabalho.descricao %>
</p>

<%= link_to 'Edit', edit_trabalho_path(@trabalho) %> |
<%= link_to 'Back', trabalhos_path %>